### ISSUE TITLE
Algoritmo minimum spanning tree

### ISSUE THREAD

**Issue by a-degregorio** [marcoguerra192/PHScaffold#1]
Problema: non basta una funzione che calcoli un minimum spanning tree, vogliamo anche poter decidere il nodo di partenza.
Potremmo usare l'algoritmo di Prim:

> https://en.wikipedia.org/wiki/Prim%27s_algorithm

qui c'è anche implementato

> https://stackoverflow.com/questions/43057855/spanning-tree-on-python

Ha un complessità di O(|V|^2) che alla fine è quanto previsto da Tamal Dey, sembra ci siano anche dei modi per renderlo più veloce poi. Che ne pensi?

**Comment by marcoguerra192** [comment]
Mi pare che la questione sia un po' diversa! Noi vogliamo uno shortest path
tree, che non è necessariamente uguale al minimum spanning... MST minimizza
il peso totale di tutti gli archi a patto di mantenere il grafo connesso,
mentre SPT minimizza la somma di tutte le lunghezze pesate dei path per
ogni nodo destinazione, fissata una sorgente. In questo caso sono gli
algoritmi di Dijkstra, Floyd-Warshall o Bellman-Ford (tipo programmazione
dinamica), che devono essere eseguiti per ogni nodo sorgente, da cui
l'O(n^3), mi pare...
La funzione che dicevo sulla wiki ci dà una matrice in cui ogni riga
rappresenta la soluzione relativa ad una data sorgente, e così dovremmo
riuscire a ricostruire tutto l'albero per ogni sorgente, e risalire anche a
quali archi sono rimasti esclusi (i non-tree edges).
Ti torna? Ci ho perso un po' di tempo a pensarci ieri, se ti pare una
minchiata dimmelo :/




Il 16 Mar 2018 12:15, "a-degregorio" <notifications@github.com> ha scritto:

Problema: non basta una funzione che calcoli un minimum spanning tree,
vogliamo anche poter decidere il nodo di partenza.
Potremmo usare l'algoritmo di Prim:

https://en.wikipedia.org/wiki/Prim%27s_algorithm

qui c'è anche implementato

https://stackoverflow.com/questions/43057855/spanning-tree-on-python

Ha un complessità di O(|V|^2) che alla fine è quanto previsto da Tamal Dey,
sembra ci siano anche dei modi per renderlo più veloce poi. Che ne pensi?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/marcoguerra192/PHScaffold/issues/1>, or mute the thread

**Comment by a-degregorio** [comment]
hai ragione, mi sono sbagliato io! non avevo capito che potessimo trovare l'albero con il nodo di partenza fissato. allora ottimo, ci dobbiamo scrivere la funzione che restituisca lo spt fissato un punto p e di conseguenza quella che restituisca il cammino minimo tra due nodi; dovremmo anche metterci in mezzo quel discorso del labelling a pag. 5 di "Efficient algorithms etc...".  
tu su cosa stai lavorando al momento?

**Comment by marcoguerra192** [comment]
Yes, mi pare di sì!
Al momento, per come è strutturato il metodo di ricerca sul grafo, il
labelling andrà per forza messo brutalmente in una matrice esterna del tipo
L(p,u) = label del vertice u nello SPT centrato in p. Al momento c'è da
finire l'algoritmo per ricostruire lo shortest path tree, e poi penso di
mettere il tutto non in uno script .ipynb ma in un file .py che fornisca
una classe con tutti i metodi implementati, così possiamo richiamarla in
una riga da un nuovo script e andare avanti :)
Tu invece?

A presto!
Marco

Il giorno 16 marzo 2018 16:29, a-degregorio <notifications@github.com> ha
scritto:

**Comment by marcoguerra192** [comment]
Ciao!
Esattamente, sto cercando di implementare quella parte in modo un minimo
efficiente! Poi appena abbiamo il codice che funziona conviene vederci,
metterci al passo a vicenda e decidere il prossimo passo...
A presto!

Il Lun 19 Mar 2018, 12:45 a-degregorio <notifications@github.com> ha
scritto:
